workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 15
    environment:
      android_signing:
        - manas
      vars:
        PACKAGE_NAME: "com.example.salestracker"
    scripts:
      - name: Build Signed Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
