workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 15
    environment:
      android_signing:
        - SalesTrackerKeystore
      vars:
        PACKAGE_NAME: "com.example.salestracker"
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk

